### ISSUE TITLE
Step 1E: Task type to task type relationship

### ISSUE THREAD

**Issue by anilmndl** [anilmndl/taskmgmt#104]
We need a way to know which task type is assigned to when new tasks are created when a task ends. Not all task completion trigger new task creation but some do. 

Create a many-to-many relationship with task types. Yes, you read it right. Task type table will have many-to-many relationship with itself. 

This is a tough task. Create mock-up UI and get feedback before implementing it.

Acceptance Criteria

- Develop a user interface where we can assign one or more task types to a specific task type.
- In the task type detail view, display a list of task types each task type is linked to.
- Make sure we cannot add the same task type more than once.
- Create a functionality to remove a task type from the relationship.

Worth double points 

Dev: Kaushal
CR: Kishor

**Comment by simkkish** [comment]
Looks good there is some inline comment.
