### ISSUE TITLE
merge problem

### ISSUE THREAD

**Issue by SanRIZZ** [anilmndl/taskmgmt#112]
guys please fix this.
![screenshot 156](https://user-images.githubusercontent.com/32321163/37887248-f59d41ac-307d-11e8-828f-40b541e1a552.png)

**Comment by Carpbra3** [comment]
What is it that you are confused about here? I see some problems in this screenshot that should be jumping out at you. I'm not sure what Anil taught you about conflict resolution, but let me know know if you don't see the problem. I'll keep an eye on this issue today.

**Comment by anilmndl** [comment]
@simkkish looking at the commit history, looks like you have introduced this error. Please fix it asap.

**Comment by SanRIZZ** [comment]
@Carpbra3  the error was because of merge conflict. He probably forgot delete redundant things while he had merge conflict.
 I hope @simkkish  will fix this soon.
Its a minor fix anyone can fix it. But I was hoping @simkkish might get something out by fixing it himself.
