### ISSUE TITLE
Search in roles

### ISSUE THREAD

**Issue by pokhalan** [anilmndl/taskmgmt#122]
I can't see your code anywhere. @simkkish  and I fixed the thing that was there(which was not working).

**Comment by pathsush** [comment]
![git1](https://user-images.githubusercontent.com/32222516/38140649-f6a34caa-33f1-11e8-80ab-ff6ae95104c2.PNG)
But i am being able to view the code and it is working perfectly on my laptop.

**Comment by pokhalan** [comment]
It did not work on mine when I tried to use it. It did not search anything.
