### ISSUE TITLE
Search for phone number not completed

### ISSUE THREAD

**Issue by pokhalan** [anilmndl/taskmgmt#123]
I can't search by a phone number. Are you working on it?

**Comment by kaushalwagle** [comment]
The phone number is integer and the search query is string, couldn't cast well to make it work.
I am still on it.

**Comment by anilmndl** [comment]
Save the phone number as a String. Often times phones numbers has '+' or '00' in the beginning and integer won't accommodate that. Saving simply as string solves all those problems.
