### ISSUE TITLE
User create failed

### ISSUE THREAD

**Issue by anilmndl** [anilmndl/taskmgmt#127]
Not sure how to create a new user, it keeps on saying something failed. Please streamline this process and make it easier to add users.

Clearly mark field that are required.
Provide clear instructions about what failed. 
UI is a bit messed up. See image

Smarty street integration is working though.

![image](https://user-images.githubusercontent.com/522954/38148078-2099215e-3412-11e8-9b56-5d3cb4370e9e.png)

Dev: Kaushal
CR: Sabin

**Comment by SanRIZZ** [comment]
@kaushalwagle are u working on it? u need any help?
