### ISSUE TITLE
couldn't initialize proxy Error

### ISSUE THREAD

**Issue by shreamar** [anilmndl/taskmgmt#140]
related to #132 

![image](https://user-images.githubusercontent.com/33479775/38437773-c2066a6e-3995-11e8-84c6-05819b993c2c.png)

Never seen this kind of error before and don't know how to deal with this.

**Comment by Carpbra3** [comment]
It's hard to tell what is happening here. I don't have any of this in the copy that I just pulled from your repo. Make sure that you reset your DB if you think you added any properties to your domain class.  One thing I do know is that "users" on a "task" are not nullable ... meaning a task should ALWAYS have a user. So I am not sure why you are trying to test is "tasks.users" is == to null ... It should never be null.

On a side note ... think about changing property and variable names. As far as I can see, a TASK has a USER ... not USERS, this can make it very confusing. As for the task that you are "editing" you are passing it as TASKS (plural) when we are just editing a TASK (singular)
