### ISSUE TITLE
Develop branch isn't working

### ISSUE THREAD

**Issue by SanRIZZ** [anilmndl/taskmgmt#144]
last commit by @pathsush

**Comment by pathsush** [comment]
In my laptop, develop is working perfectly. Since I pull everything from develop.

**Comment by anilmndl** [comment]
What message are you getting?

**Comment by pathsush** [comment]
Nothing.  it runs perfectly.

**Comment by anilmndl** [comment]
Ok. I just pulled in the changes and I was able to compile it.

**Comment by SanRIZZ** [comment]
Professor Anil,
You need to delete your database and create new one. It will work then

**Comment by anilmndl** [comment]
It's working on mine. I think is wasn't working on yours.

**Comment by SanRIZZ** [comment]
Ohh wait..
This was an old issue..
It should be closed..
