### ISSUE TITLE
Issues why task workflow is failing when one task is marked completed.

### ISSUE THREAD

**Issue by anilmndl** [anilmndl/taskmgmt#182]
**Problem I**

https://github.com/anilmndl/taskmgmt/blob/8681c304fe6b256a039e6e4fa2113b39a185a02b/grails-app/controllers/taskmgmt/TaskController.groovy#L29

If you notice this action, you are trying to render a gsp page in the exception block. When an exception is throws, Grails automatically detaches the link between the instance of a class and the Hibernate (the underlying library that manages connection to the database) session.  This is why you get LazyInitializationException. This basically means that object is no longer linked to the Hibernate session. 
Read more here: http://docs.grails.org/3.1.1/ref/Domain%20Classes/attach.html

To fix this,  DO NOT redirect on line 33  and DO NOT render a view on line 37. Instead redirect to the detail action using this code outside of try...catch block.

redirect action: "detail", id: task.id

**Problem II**

https://github.com/anilmndl/taskmgmt/blob/8681c304fe6b256a039e6e4fa2113b39a185a02b/grails-app/services/taskmgmt/TaskService.groovy#L70

You are using collect closure. Remember that it returns a new collection. You are expecting here that it will return a list of users that are not in vacation. However, it returning a list of Boolean. You need to replace this with findAll closure. 

**Problem III**
https://github.com/anilmndl/taskmgmt/blob/8681c304fe6b256a039e6e4fa2113b39a185a02b/grails-app/services/taskmgmt/TaskService.groovy#L75

Here you are expecting that the size of usersNotInVacation will never be zero. You need to test for that and if there are no users in the usersNotInVacation, then there is not user assigned to that task.

Hope this clears some confusions.

**Comment by SanRIZZ** [comment]
Professor anil. I have tried a new criteria and still it returns current logged in user null.
![image](https://user-images.githubusercontent.com/32321163/39361789-34f49b30-49e1-11e8-88f4-25d171685ec9.png)

**Comment by SanRIZZ** [comment]
done
