### ISSUE TITLE
What is this flag for?

### ISSUE THREAD

**Issue by anilmndl** [anilmndl/taskmgmt#33]
https://github.com/anilmndl/taskmgmt/blob/185e8795999adda199a0231d61f2d67caa14132c/grails-app/domain/taskmgmt/Task.groovy#L14

I am not sure what is 'flag' for?

**Comment by simkkish** [comment]
Fixed

**Comment by anilmndl** [comment]
I do not see any commit tied to issue. Please learn how to tie a specific commit to an issue.
