### ISSUE TITLE
Someone messed up develop

### ISSUE THREAD

**Issue by SanRIZZ** [anilmndl/taskmgmt#35]
I just checked develop and its messed up.. it doesn't work. I have added my changes(which works) to it still there are many error....
I am working on to fix all those... 
Guys please fully test your branches before you push.
I will push the new updated one soon and notify all and close this issue.

**Comment by SanRIZZ** [comment]
So guys the errors were... variable initialization as we talked in class. there were number of places where task type variable was called tsktype and the major issue was tasktype. Task type is called as tag in our back end... but people who made front end messed up and used title as name so the save and all others weren't working. I strongly urge u to please update this new update and then work forward.

**Comment by SanRIZZ** [comment]
if u guys have all read this then only close the issue.. thanks

**Comment by anilmndl** [comment]
Thanks Sabin for taking lead on this issue. I already see several issue in the projects but I want you guys to find it out.
