### ISSUE TITLE
There is no use for this

### ISSUE THREAD

**Issue by anilmndl** [anilmndl/taskmgmt#40]
https://github.com/anilmndl/taskmgmt/blob/d318bc2c2cfa47157b7e39fc20d97507068119d8/grails-app/taglib/taskmgmt/DeleteTagLib.groovy#L3

What is the purpose of this TagLib?

**Comment by SanRIZZ** [comment]
someone created it and I have no idea why there is smthg like that
i will fix it by tommorow i hope.. i have exam tomorrow and day after tomorrow. I will try but no promises. And same goes for other issues.... except critical ones

**Comment by anilmndl** [comment]
Work on the assignments first.

**Comment by anilmndl** [comment]
@simkkish looks like you created this file. Could you explain why this was created in the first place?

**Comment by simkkish** [comment]
I was trying to work in before the detail page and at the end I forgot to delete.
