### ISSUE TITLE
Soft Date deleted

### ISSUE THREAD

**Issue by simkkish** [anilmndl/taskmgmt#44]
https://github.com/anilmndl/taskmgmt/blob/0c7ffe920901deb8f55d1b53e701a79767cfffbc/grails-app/services/taskmgmt/TaskService.groovy#L32
Should we use the Enum or Date dateDeleted?

**Comment by anilmndl** [comment]
Use the date to indicate if the task is deleted. That way we have a record of when the task was deleted.
