### ISSUE TITLE
Couldn't figure out why this unit test is not working

### ISSUE THREAD

**Issue by shreamar** [anilmndl/taskmgmt#46]
https://github.com/anilmndl/taskmgmt/blob/533e12caa572b68173e81ea697fdd187304f0ec1/grails-app/controllers/taskmgmt/TaskTypeController.groovy#L31

```
void "task_type_update_action"() {

        when:

        def taskType = new TaskType(title: "title")

        controller.save(taskType)

        int version = taskType.version

        controller.update()
        
        then:

        response.status == 302

        version != taskType.version

    }
```

I've written this unit test that tests the update method() of TaskType Controller. But it gives me this error.
![image](https://user-images.githubusercontent.com/33479775/36870457-60b62330-1d5c-11e8-9381-bf8aa8cdf068.png)

I actually created instance of TaskType object (`def TaskType = new TaskType(title: "title")`), but it still tells me that the object is null. Spent hours figuring this out but couldn't find what I'm doing wrong.

**Comment by anilmndl** [comment]
You are using a service in line number 18 for TaskTypeController to save the task. In Unit Tests, you have to mock services as well. Don't worry about it right now. I will send you a sample code to fix this. There are more moving parts in this than I can explain here.

For now only test actions that do not user services.
