### ISSUE TITLE
TaskStatus shouldn't maintain the delete state of a task. 

### ISSUE THREAD

**Issue by anilmndl** [anilmndl/taskmgmt#51]
https://github.com/anilmndl/taskmgmt/blob/73f516a0a2e26a4b79bae61c6dd1a0f9768a93c0/src/main/groovy/taskmgmt/enums/TaskStatus.groovy#L9

I don't think its a good architecture to to use TaskStatus to find out if the task was deleted or not. In the Task domain, we have deletedDate. For any task that are deleted, set the date value in this property.  When creating SQL queries, we only get tasks whose deletedDate is null.

Technically this works and there is nothing that stops us from doing it, it having a separate property to manage this would be better in the long run.

I hope that makes sense.

In this service, instead of setting taskStatus, use dataDeleted = new Date()
https://github.com/anilmndl/taskmgmt/blob/73f516a0a2e26a4b79bae61c6dd1a0f9768a93c0/grails-app/services/taskmgmt/TaskService.groovy#L19

**Comment by shreamar** [comment]
Alright. I'll fix it. I thought since it has all other status like COMPLETED, MODIFIED, it would also make sense to add DELETED.
