### ISSUE TITLE
TaskType delete

### ISSUE THREAD

**Issue by anilmndl** [anilmndl/taskmgmt#61]
The current user interface for delete is very dangerous. It's so close to the edit button that a user may accidentally click it and the task type is deleted without warning. 

Move the _delete_ button to the task type detail view. That way they have to view the details of a task type before they can delete it. 

Also there is a security issue. A tech savvy person can identify that you are passing an **id** in the url and he/she can generate url to delete all task types. Make sure the _delete_ action only accepts POST form submission.

**Comment by SanRIZZ** [comment]
Hi Amar,
It was my work...
You were CR.
