### ISSUE TITLE
Pagination TaskType pagination

### ISSUE THREAD

**Issue by anilmndl** [anilmndl/taskmgmt#64]
If there are more than 10 task type, it should paginate.

**Comment by shreamar** [comment]
Maybe number of data displayed per page should be decreased

https://github.com/anilmndl/taskmgmt/blob/ba40c0069c46737dfcda7bc7170149648a5f1fd8/grails-app/views/task/list.gsp#L84

And also needs some finishing in it's UI

**Comment by pathsush** [comment]
It work perfectly fine when  i run application directly from develop
