### ISSUE TITLE
Task detail view need improvments

### ISSUE THREAD

**Issue by anilmndl** [anilmndl/taskmgmt#68]
The task detail view needs improvements.

Why do we have search bar on the detail view?
Why do we have an _Unlocked_ button if the task was never locked?
Why do we have an _Locked_ button if the task was already locked?
In the detail view, I should be able to see what is the current status of the task
Use your judgement to improve this page and make it more user friendly.

Dev: Amar - self assigned
CR: Kishor

**Comment by simkkish** [comment]
Looks good. View is well organized and displayed.  good job overall.
