### ISSUE TITLE
Task search

### ISSUE THREAD

**Issue by anilmndl** [anilmndl/taskmgmt#69]
implement this

A user should be able to search task by _title,_ _dateCreated,_ task type and _status_

**Comment by anilmndl** [comment]
CR pokhalan

**Comment by simkkish** [comment]
Working on it

**Comment by pokhalan** [comment]
Are you almost done??

**Comment by simkkish** [comment]
Yes i am struggling with searching through date. I will push it today afternoon.

**Comment by SanRIZZ** [comment]
needs work on to be searched by taskType.
we can now search by date and title.
@anilmndl  Will I get extra credit for doing search by date??
@simkkish  helped while making this too
