### ISSUE TITLE
Customer Address

### ISSUE THREAD

**Issue by anilmndl** [anilmndl/taskmgmt#76]
Customer address should be on a separate table

**Comment by kaushalwagle** [comment]
@anilmndl 
How do I save address first and then link that to the user with one submit button?

**Comment by anilmndl** [comment]
https://docs.grails.org/latest/ref/Domain%20Classes/addTo.html

**Comment by kaushalwagle** [comment]
@anilmndl  I understand that, but how to associate params of both user and address in that function
https://github.com/anilmndl/taskmgmt/blob/09bf3b508595547a8c54b089bbddbbbff1e6a8fa/grails-app/controllers/taskmgmt/UserController.groovy#L16

is it 
def save(User user, Address address){

**Comment by anilmndl** [comment]
That is one way to solve the problem as long as proper fields name match with the respective domain.
When persisting the data to the database, make sure it saved and the two domain object are linked to each other, otherwise you will have orphaned data.

Another way is to create command object. Command object is similar to a domain except it is not linked to the database.
http://guides.grails.org/command-objects-and-forms/guide/index.html

**Comment by pathsush** [comment]
Dev:- Sushil
