### ISSUE TITLE
Having issue compiling the code

### ISSUE THREAD

**Issue by shreamar** [anilmndl/taskmgmt#77]
![image](https://user-images.githubusercontent.com/33479775/37240130-85efafc8-2404-11e8-851b-1c8497c4c442.png)
I got this error when I tried to run the taskmgmt grails app.
What could be possible solutions to this problem?

**Comment by Carpbra3** [comment]
Hey Amar, did you change any type of configuration or anything?

**Comment by anilmndl** [comment]
This usually happens when the Gradle dependency file is corrupt.

Go to _build_ folder. Delete the _.dependencies_ file and run the application again. Gradle will rebuild the dependency file and hopefully the issue is resolved.

**Comment by Carpbra3** [comment]
Amar, did this get resolved?

**Comment by shreamar** [comment]
Yes thank you @anilmndl  and @Carpbra3  for helping me out. The problem was with dependencies. I followed what @anilmndl suggested and it works fine now.
