### ISSUE TITLE
Having issue when compiling

### ISSUE THREAD

**Issue by pathsush** [anilmndl/taskmgmt#78]
I didn't change anything but when I restart my computer and try to run the code it throws this error out of nowhere. Also, I tried to make new database connections but it doesn't work. 
![capture](https://user-images.githubusercontent.com/32222516/37328226-fcfe7390-265e-11e8-80ce-ba9365f57e84.PNG)

**Comment by anilmndl** [comment]
Make sure you can log in to SQL server with a correct user and password. Also make sure the same username and password is used in _application.yml_ file

**Comment by pathsush** [comment]
It works when I update my password to sa. But, I believe username should be sa and password should be empty for the database.

**Comment by Carpbra3** [comment]
If it worked when you updated your password to that ... that would mean that is how that database is setup. If it is working, just leave it and we can look into how that change happened in class.
