### ISSUE TITLE
Customer create

### ISSUE THREAD

**Issue by anilmndl** [anilmndl/taskmgmt#83]
As a user I see "Error 500: Internal Server Error" when I submit the form without filling out all the information. This is scary for a user.

I would like to see clear indicators to identify which fields are required, I shouldn't able to submit the form without filling out required forms. 

Once the customer is successfully save, I should be redirected to the customer detail view to make sure the information I typed in were correct.

Dev: Amar - self assigned3
CR: Alankar

**Comment by pokhalan** [comment]
it worked perfectly for me. The fields that are required had a required field inside it which makes sure it is filled before submitting. It goes to the 1st page of the detail page.
Errors: 
1) It does not go to the detail page where the user is added(that is the last page).

Everything else works great.

**Comment by shreamar** [comment]
Resolved
