### ISSUE TITLE
Customer accidental delete

### ISSUE THREAD

**Issue by anilmndl** [anilmndl/taskmgmt#84]
Clicking on the delete button deletes the customer without any confirmation. 

Display a Bootstrap modal or similar functionality (do not use javascript alert, some browsers block the popups) to ask for a confirmation before deleting a customer.

Dev: Amar - self assigned
CR: Sushil

**Comment by anilmndl** [comment]
@shreamar , @pathsush please finish this asap.

**Comment by pathsush** [comment]
Completed.
