### ISSUE TITLE
Link to the task type name gives an error

### ISSUE THREAD

**Issue by asimdhakal** [anilmndl/taskmgmt#96]
When the task type name is clicked on the task type list page, it throws an error.

![image](https://user-images.githubusercontent.com/17816478/37686886-f9c6d6b2-2c5e-11e8-99b3-46ba8569f4dc.png)

**Comment by pathsush** [comment]
Can you please pull the code from develop. Develop branch had been modified and solved this issue on Monday?

**Comment by asimdhakal** [comment]
Yes, looks like this issue is fixed.
