### ISSUE TITLE
Confusion in pagination

### ISSUE THREAD

**Issue by pathsush** [anilmndl/taskmgmt#97]
I paginate the task and task types. It only paginates, when I go to the second page and come back to the first page. Is there a specific way to set a default pagination from the first page without going to 2nd page?

**Comment by anilmndl** [comment]
You would want to set the default max value for the params.

eg. 

params.max = 20

**Comment by pathsush** [comment]
I think by default it paginates to 10. So,  when I click list task it doesn't paginate. It only paginates when I click the page number.

**Comment by anilmndl** [comment]
You are missing the point. When you load the list page loads, is there anything that tells the system that it should only load the first 10 items.

**Comment by pathsush** [comment]
My Bad!! I got it.
