### ISSUE TITLE
Step IA: Spawn new tasks on task completion

### ISSUE THREAD

**Issue by anilmndl** [anilmndl/taskmgmt#99]
Create a functionality where the system can create one or more tasks when a task is marked completed.

A new feature is requested. When a current task is marked "COMPLETED", new tasks need to be created. One or more new tasks may be created. The details about how many tasks need to be created will follow in issue #101 

Acceptance Criteria

- Create some random tasks when one task is completed.
- Assign the newly created tasks to a random user.

Dev: Alankar
CR: Kaushal

**Comment by pokhalan** [comment]
Completed
